Repository remkop/picocli, pull requests merged in 2018-10, with the labels that each got.

#510 Fix doc link for moved example files
  docs/index.adoc
  docs/quick-guide.adoc
Labels: bug, doc

#523 Fill array values before setting them as value
  src/main/java/picocli/CommandLine.java
  src/test/java/picocli/CommandLineTest.java
Labels: bug

#525 Allow @Mixin to be used for methods as well
  src/main/java/picocli/CommandLine.java
  src/test/java/picocli/CommandLineCommandMethodTest.java
  src/test/java/picocli/CommandLineMixinTest.java
Labels: API, enhancement

#532 Add a way to get the argument attempted to be overwritten from an OverwrittenOptionException
  src/main/java/picocli/CommandLine.java
  src/test/java/picocli/CommandLineTest.java
Labels: API, enhancement
