Repository remkop/picocli, pull requests merged in 2021-02, with the labels that each got.

#1321 Fix bad encoding when creating default PrintWriter
  src/main/java/picocli/CommandLine.java
  src/test/java/picocli/ExecuteTest.java
  src/test/java/picocli/HelpSubCommandTest.java
  src/test/java/picocli/Issue1320.java
Labels: bug, enhancement, shell

#1327 chore: fix incorrect version in MANIFEST.MF
  build.gradle
  picocli-annotation-processing-tests/build.gradle
  picocli-codegen/build.gradle
  picocli-groovy/build.gradle
  picocli-shell-jline2/build.gradle
  picocli-shell-jline3/build.gradle
  picocli-spring-boot-starter/build.gradle
Labels: bug

#1332 Bumping asciidoctor + asciidoctor gradle plugin to latest versions
  build.gradle
  gradle.properties
  picocli-examples/generate-man-pages/example-gradle-project/build.gradle
Labels: build, dependency, doc
