Repository remkop/picocli, pull requests merged in 2021-12, with the labels that each got.

#1484 Fixed org.junit.Assert.assertThat deprecation warning
  picocli-annotation-processing-tests/src/test/java/picocli/annotation/processing/tests/YamlAssert.java
Labels: enhancement

#1493 PositionalParamSpec changed to max
  src/main/java/picocli/CommandLine.java
Labels: bug, arg-group

#1500 Bump gradle from 7.3 to 7.3.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependency, build

#1502 Kedo issue1383
  src/test/java/picocli/MultipleArgumentsTest.java
Labels: doc

#1517 Bump gradle from 7.3.1 to 7.3.3
  gradle/wrapper/gradle-wrapper.properties
Labels: dependency
