Repository remkop/picocli, pull requests merged in 2022-02, with the labels that each got.

#1568 CommandLine cleanup
  src/main/java/picocli/CommandLine.java
Labels: enhancement

#1569 Bump gradle from 7.3.3 to 7.4
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build

#1505 [#1380] Fix for requiredOptionMarker displayed on ArgGroup
  picocli-annotation-processing-tests/src/test/java/picocli/Issue1380Test.java
  picocli-annotation-processing-tests/src/test/java/picocli/Issue1420Test.java
  picocli-annotation-processing-tests/src/test/resources/picocli/Message.properties
  src/main/java/picocli/CommandLine.java
Labels: API, usagehelp
