Repository remkop/picocli, pull requests merged in 2022-01, with the labels that each got.

#1530 Simplified CommandSpec#validateSubcommandName(…)
  src/main/java/picocli/CommandLine.java
Labels: enhancement

#1545 Add NOTICE file
  NOTICE
Labels: doc

#1518 Simplified detection of getter & setter in TypedMember constructor
  src/main/java/picocli/CommandLine.java
Labels: enhancement

#1548 [#1526] Fix use of compinit clobbering existing completions
  src/main/java/picocli/AutoComplete.java
  src/test/java/picocli/AutoCompleteTest.java
  src/test/resources/bashify_completion.bash
  src/test/resources/basic.bash
  src/test/resources/hyphenated_completion.bash
  src/test/resources/picocompletion-demo-help_completion.bash
  src/test/resources/picocompletion-demo_completion.bash
Labels: enhancement, auto-completion
