Repository remkop/picocli, pull requests merged in 2023-01, with the labels that each got.

#1908 Use the new official native-maven-plugin
  docs/index.adoc
Labels: type: doc :blue_book:

#1911 Avoid using boxed boolean in applyValueToSingleValuedField
  src/main/java/picocli/CommandLine.java
Labels: type: enhancement :sparkles:

#1917 Fixes broken link in README.md (#1910)
  README.md
Labels: type: doc :blue_book:

#1920 README.md: remove unused travis badge
  .travis.yml
  README.md
Labels: type: enhancement :sparkles:, type: doc :blue_book:, theme: build
